In [2]:
import numpy as np
import os
import  sys

In [3]:
# initializing an array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.3,1.5],[6.1,5.0,2.8]])
print(b)

[[9.  8.3 1.5]
 [6.1 5.  2.8]]


In [5]:
#get dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Data type
print(a.dtype)
print(b.dtype)

int32
float64


In [8]:
# Get element item size
print(a.itemsize)
print(b.itemsize)


4
8


# Accessing/Changing elements,rows,columns

In [10]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[90,91,92,93,94,95,96]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [90 91 92 93 94 95 96]]


In [12]:
#get a specific element [row,col]
c[2, 5]

95

In [13]:
# get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
c[:,4]

array([ 5, 12, 94])

In [15]:
# slicing with step size
c[0,1:6:3]

array([2, 5])

## Initializing Arrays

In [24]:
z = np.zeros((2,3))
print(z)


[[0. 0. 0.]
 [0. 0. 0.]]
